
export type Option = {
  value: string
  label: string
}


export const coffeeProducingCountries: Option[] = [
  { value: "brazil", label: "Brazil" },
  { value: "vietnam", label: "Vietnam" },
  { value: "colombia", label: "Colombia" },
  { value: "indonesia", label: "Indonesia" },
  { value: "ethiopia", label: "Ethiopia" },
  { value: "honduras", label: "Honduras" },
  { value: "india", label: "India" },
  { value: "uganda", label: "Uganda" },
  { value: "mexico", label: "Mexico" },
  { value: "guatemala", label: "Guatemala" },
  { value: "peru", label: "Peru" },
  { value: "nicaragua", label: "Nicaragua" },
  { value: "china", label: "China" },
  { value: "ivory-coast", label: "Ivory Coast" },
  { value: "costa-rica", label: "Costa Rica" },
  { value: "kenya", label: "Kenya" },
  { value: "tanzania", label: "Tanzania" },
  { value: "el-salvador", label: "El Salvador" },
  { value: "ecuador", label: "Ecuador" },
  { value: "cameroon", label: "Cameroon" },
  { value: "laos", label: "Laos" },
  { value: "madagascar", label: "Madagascar" },
  { value: "gabon", label: "Gabon" },
  { value: "thailand", label: "Thailand" },
  { value: "venezuela", label: "Venezuela" },
  { value: "dominican-republic", label: "Dominican Republic" },
  { value: "haiti", label: "Haiti" },
  { value: "democratic-republic-of-congo", label: "Democratic Republic of Congo" },
  { value: "rwanda", label: "Rwanda" },
  { value: "burundi", label: "Burundi" },
  { value: "philippines", label: "Philippines" },
  { value: "togo", label: "Togo" },
  { value: "guinea", label: "Guinea" },
  { value: "yemen", label: "Yemen" },
  { value: "cuba", label: "Cuba" },
  { value: "panama", label: "Panama" },
  { value: "bolivia", label: "Bolivia" },
  { value: "jamaica", label: "Jamaica" },
  { value: "puerto-rico", label: "Puerto Rico" },
  { value: "papua-new-guinea", label: "Papua New Guinea" },
  { value: "zimbabwe", label: "Zimbabwe" },
  { value: "hawaii", label: "Hawaii" },
]

export const varieties = [
  { value: "gesha", label: "Gesha" },
  { value: "pacamara", label: "Pacamara" },
  { value: "maragogipe", label: "Maragogipe" },
  { value: "sl-28", label: "SL-28" },
  { value: "sl-34", label: "SL-34" },
  { value: "bourbon", label: "Bourbon" },
  { value: "pink-bourbon", label: "Pink Bourbon" },
  { value: "typica", label: "Typica" },
  { value: "caturra", label: "Caturra" },
  { value: "catuai", label: "Catuai" },
  { value: "ethiopian-heirloom", label: "Ethiopian Heirloom" },
  { value: "pacas", label: "Pacas" },
  { value: "mundo-novo", label: "Mundo Novo" },
  { value: "villa-sarchi", label: "Villa Sarchi" },
  { value: "ihcafe-90", label: "IHCAFE 90" },
  { value: "lempira", label: "Lempira" },
  { value: "parainema", label: "Parainema" },
  { value: "catimor", label: "Catimor" },
  { value: "sarchimor", label: "Sarchimor" },
  { value: "rume-sudan", label: "Rume Sudan" },
  { value: "javanica", label: "Javanica" },
  { value: "k7", label: "K7" },
  { value: "batian", label: "Batian" },
  { value: "obata", label: "Obatã" },
  { value: "tupi", label: "Tupi" },
  { value: "colombia", label: "Colombia" },
  { value: "castillo", label: "Castillo" },
  { value: "anacafe-14", label: "Anacafé 14" },
  { value: "bourbon-pointu", label: "Bourbon Pointu" },
  { value: "liberica", label: "Liberica" },
  { value: "excelsa", label: "Excelsa" },
];

export const coffeeTastingNotes = [
  { value: "chocolate", label: "Chocolate" },
  { value: "dark_chocolate", label: "Dark Chocolate" },
  { value: "milk_chocolate", label: "Milk Chocolate" },
  { value: "cocoa", label: "Cocoa" },
  { value: "caramel", label: "Caramel" },
  { value: "toffee", label: "Toffee" },
  { value: "molasses", label: "Molasses" },
  { value: "brown_sugar", label: "Brown Sugar" },
  { value: "honey", label: "Honey" },
  { value: "maple", label: "Maple" },
  { value: "butterscotch", label: "Butterscotch" },
  { value: "vanilla", label: "Vanilla" },
  { value: "hazelnut", label: "Hazelnut" },
  { value: "almond", label: "Almond" },
  { value: "walnut", label: "Walnut" },
  { value: "pecan", label: "Pecan" },
  { value: "peanut_butter", label: "Peanut Butter" },
  { value: "citrus", label: "Citrus" },
  { value: "orange", label: "Orange" },
  { value: "lemon", label: "Lemon" },
  { value: "lime", label: "Lime" },
  { value: "grapefruit", label: "Grapefruit" },
  { value: "tangerine", label: "Tangerine" },
  { value: "berry", label: "Berry" },
  { value: "strawberry", label: "Strawberry" },
  { value: "raspberry", label: "Raspberry" },
  { value: "blueberry", label: "Blueberry" },
  { value: "blackberry", label: "Blackberry" },
  { value: "cranberry", label: "Cranberry" },
  { value: "cherry", label: "Cherry" },
  { value: "dried_fruit", label: "Dried Fruit" },
  { value: "raisin", label: "Raisin" },
  { value: "date", label: "Date" },
  { value: "fig", label: "Fig" },
  { value: "prune", label: "Prune" },
  { value: "apple", label: "Apple" },
  { value: "pear", label: "Pear" },
  { value: "peach", label: "Peach" },
  { value: "apricot", label: "Apricot" },
  { value: "plum", label: "Plum" },
  { value: "mango", label: "Mango" },
  { value: "pineapple", label: "Pineapple" },
  { value: "papaya", label: "Papaya" },
  { value: "melon", label: "Melon" },
  { value: "banana", label: "Banana" },
  { value: "grape", label: "Grape" },
  { value: "floral", label: "Floral" },
  { value: "jasmine", label: "Jasmine" },
  { value: "hibiscus", label: "Hibiscus" },
  { value: "honeysuckle", label: "Honeysuckle" },
  { value: "lavender", label: "Lavender" },
  { value: "rose", label: "Rose" },
  { value: "herbal", label: "Herbal" },
  { value: "mint", label: "Mint" },
  { value: "thyme", label: "Thyme" },
  { value: "sage", label: "Sage" },
  { value: "lemongrass", label: "Lemongrass" },
  { value: "green_tea", label: "Green Tea" },
  { value: "black_tea", label: "Black Tea" },
  { value: "spice", label: "Spice" },
  { value: "cinnamon", label: "Cinnamon" },
  { value: "clove", label: "Clove" },
  { value: "nutmeg", label: "Nutmeg" },
  { value: "cardamom", label: "Cardamom" },
  { value: "anise", label: "Anise" },
  { value: "pepper", label: "Pepper" },
  { value: "ginger", label: "Ginger" },
  { value: "earthy", label: "Earthy" },
  { value: "mushroom", label: "Mushroom" },
  { value: "woody", label: "Woody" },
  { value: "tobacco", label: "Tobacco" },
  { value: "leather", label: "Leather" },
  { value: "smoky", label: "Smoky" },
  { value: "roasted", label: "Roasted" },
  { value: "malty", label: "Malty" },
  { value: "bready", label: "Bready" },
  { value: "grain", label: "Grain" },
  { value: "buttery", label: "Buttery" },
  { value: "creamy", label: "Creamy" },
  { value: "savory", label: "Savory" },
  { value: "umami", label: "Umami" },
  { value: "sweet", label: "Sweet" },
  { value: "syrupy", label: "Syrupy" },
  { value: "juicy", label: "Juicy" },
  { value: "winey", label: "Winey" },
  { value: "fermented", label: "Fermented" },
  { value: "acidic", label: "Bright / Acidic" },
  { value: "clean", label: "Clean" },
  { value: "balanced", label: "Balanced" },
  { value: "complex", label: "Complex" },
  { value: "smooth", label: "Smooth" },
  { value: "silky", label: "Silky" },
  { value: "velvety", label: "Velvety" },
  { value: "dry", label: "Dry" },
  { value: "crisp", label: "Crisp" },
  { value: "tangy", label: "Tangy" },
  { value: "tart", label: "Tart" },
  { value: "sour", label: "Sour" },
  { value: "nutty", label: "Nutty" },
  { value: "carbony", label: "Carbony" },
  { value: "ashy", label: "Ashy" },
  { value: "spicy", label: "Spicy" },
  { value: "fruity", label: "Fruity" },
  { value: "tropical", label: "Tropical" },
  { value: "stone_fruit", label: "Stone Fruit" },
  { value: "tamarind", label: "Tamarind" },
  { value: "green_apple", label: "Green Apple" },
  { value: "grapey", label: "Grapey" },
  { value: "jujube", label: "Jujube" },


  // More Specific Fruits (Tropical/Other)
  { value: "lychee", label: "Lychee" },
  { value: "passion_fruit", label: "Passion Fruit" },
  { value: "guava", label: "Guava" },
  { value: "coconut", label: "Coconut" },
  { value: "pomegranate", label: "Pomegranate" },

  // Vegetal / Green / Other
  { value: "vegetative", label: "Vegetative/Green" },
  { value: "hay", label: "Hay-like" },
  { value: "grass", label: "Grass/Grassy" },
  { value: "bell_pepper", label: "Bell Pepper" },
  { value: "olive", label: "Olive" },
  { value: "chlorine", label: "Chlorine-like" }, 
  { value: "rubber", label: "Rubber" }, 

  // Roast / Carbon
  { value: "bittersweet", label: "Bittersweet" },
  { value: "burnt_sugar", label: "Burnt Sugar/Crème Brûlée" },
  { value: "toast", label: "Toast" },
  { value: "charcoal", label: "Charcoal" },

  // Sweet / Nutty
  { value: "marzipan", label: "Marzipan" },
  { value: "pecan_pie", label: "Pecan Pie" }, 
  { value: "agave", label: "Agave" },
  { value: "panela", label: "Panela" },

  // Spices (Warm/Earthy)
  { value: "allspice", label: "Allspice" },
  { value: "licorice", label: "Licorice" },
  { value: "fennel", label: "Fennel" },

  // Mouthfeel / Body
  { value: "round", label: "Round/Well-Rounded" },
  { value: "heavy", label: "Heavy-bodied" },
  { value: "astringent", label: "Astringent" }, // Mouth-drying
  { value: "pithy", label: "Pithy" } 

];


export function getLabelFromValue(options: Option[], value?: string): string {
  if (!value) return "Unknown"
  return options.find((o) => o.value === value)?.label ?? value
}

// export function getValueFromLabel(options: Option[], label?: string): string {
//   if (!label) return ""
//   return options.find((o) => o.label === label)?.value ?? label.toLowerCase()
// }
